export const data = {
    projects: [
      {
        id:1,
        image:"compositor.jpg",
        title: "Model 3",
        category: "Car",
        price:49040,
        reduceprice:50490,
        description: "",
      },
      {
        id:2,
        image:"compositor1.jpg",
        title: "Model S",
        category: "Car",
        price:77020,
        reduceprice:82990,
        description: "",
      },
      {
        id:3,
        image:"compositor2.jpg",
        title: "Model X",
        category: "Car",
        price:80570,
        reduceprice:86490,
        description: "",
      },
      {
        id:4,
        image:"compositor3.jpg",
        title: "Model Y",
        category: "Car",
        price:53510,
        reduceprice:55490,
        description: "Model Y Performance Dual Motor All-Wheel Drive",
      },
      {
        id:5,
        image:"compositor.jpg",
        title: "Tesla semi",
        category: "Car",
        price:39040,
        reduceprice:45490,
        description: "",
      },
      {
        id:6,
        image:"compositor1.jpg",
        title: "Used Model S",
        category: "Car",
        price:50020,
        reduceprice:60990,
        description: "",
      },
    ]
  };